version: '3.8'

services:
  # app:
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
    

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=point_of_sale
    volumes:
      - db:/data/db


volumes:
  db: